package lexerAndParser;

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 14 14:34:26 GMT 2014
//----------------------------------------------------
import java_cup.runtime.*;
import ast.*;

/**
 * CUP v0.10k generated parser.
 *
 * @version Fri Feb 14 14:34:26 GMT 2014
 */
public class parser extends java_cup.runtime.lr_parser {

    /**
     * Default constructor.
     */
    public parser() {
        super();
    }

    /**
     * Constructor which sets the default scanner.
     */
    public parser(java_cup.runtime.Scanner s) {
        super(s);
    }

    /**
     * Production table.
     */
    protected static final short _production_table[][]
            = unpackFromStrings(new String[]{
                "\000\022\000\002\003\003\000\002\002\004\000\002\003"
                + "\003\000\002\003\003\000\002\003\003\000\002\003\003"
                + "\000\002\003\005\000\002\007\003\000\002\004\003\000"
                + "\002\006\004\000\002\005\003\000\002\005\003\000\002"
                + "\005\003\000\002\005\003\000\002\010\005\000\002\011"
                + "\005\000\002\012\005\000\002\013\005"});

    /**
     * Access to production table.
     */
    public short[][] production_table() {
        return _production_table;
    }

    /**
     * Parse-action table.
     */
    protected static final short[][] _action_table
            = unpackFromStrings(new String[]{
                "\000\033\000\014\010\013\011\007\014\017\017\021\022"
                + "\015\001\002\000\016\002\ufffc\005\ufffc\006\ufffc\007\ufffc"
                + "\013\ufffc\020\ufffc\001\002\000\016\002\001\005\001\006"
                + "\001\007\001\013\001\020\001\001\002\000\016\002\ufffd"
                + "\005\ufffd\006\ufffd\007\ufffd\013\ufffd\020\ufffd\001\002\000"
                + "\016\002\ufffe\005\ufffe\006\ufffe\007\ufffe\013\ufffe\020\ufffe"
                + "\001\002\000\014\002\035\005\024\006\026\007\027\013"
                + "\023\001\002\000\016\002\ufff7\005\ufff7\006\ufff7\007\ufff7"
                + "\013\ufff7\020\ufff7\001\002\000\016\002\ufff5\005\ufff5\006"
                + "\ufff5\007\ufff5\013\ufff5\020\ufff5\001\002\000\016\002\uffff"
                + "\005\uffff\006\uffff\007\uffff\013\uffff\020\uffff\001\002\000"
                + "\016\002\ufff4\005\ufff4\006\ufff4\007\ufff4\013\ufff4\020\ufff4"
                + "\001\002\000\016\002\ufffa\005\ufffa\006\ufffa\007\ufffa\013"
                + "\ufffa\020\ufffa\001\002\000\016\002\ufff6\005\ufff6\006\ufff6"
                + "\007\ufff6\013\ufff6\020\ufff6\001\002\000\014\010\013\011"
                + "\007\014\017\017\021\022\015\001\002\000\016\002\ufff9"
                + "\005\ufff9\006\ufff9\007\ufff9\013\ufff9\020\ufff9\001\002\000"
                + "\014\010\013\011\007\014\017\017\021\022\015\001\002"
                + "\000\014\005\024\006\026\007\027\013\023\020\025\001"
                + "\002\000\014\010\013\011\007\014\017\017\021\022\015"
                + "\001\002\000\014\010\013\011\007\014\017\017\021\022"
                + "\015\001\002\000\016\002\ufffb\005\ufffb\006\ufffb\007\ufffb"
                + "\013\ufffb\020\ufffb\001\002\000\014\010\013\011\007\014"
                + "\017\017\021\022\015\001\002\000\014\010\013\011\007"
                + "\014\017\017\021\022\015\001\002\000\016\002\ufff2\005"
                + "\024\006\ufff2\007\ufff2\013\ufff2\020\ufff2\001\002\000\016"
                + "\002\ufff0\005\024\006\ufff0\007\027\013\023\020\ufff0\001"
                + "\002\000\016\002\ufff3\005\ufff3\006\ufff3\007\ufff3\013\ufff3"
                + "\020\ufff3\001\002\000\016\002\ufff1\005\024\006\ufff1\007"
                + "\027\013\ufff1\020\ufff1\001\002\000\016\002\ufff8\005\ufff8"
                + "\006\ufff8\007\ufff8\013\ufff8\020\ufff8\001\002\000\004\002"
                + "\000\001\002"});

    /**
     * Access to parse-action table.
     */
    public short[][] action_table() {
        return _action_table;
    }

    /**
     * <code>reduce_goto</code> table.
     */
    protected static final short[][] _reduce_table
            = unpackFromStrings(new String[]{
                "\000\033\000\024\003\007\004\005\005\003\006\017\007"
                + "\004\010\010\011\015\012\011\013\013\001\001\000\002"
                + "\001\001\000\002\001\001\000\002\001\001\000\002\001"
                + "\001\000\002\001\001\000\002\001\001\000\002\001\001"
                + "\000\002\001\001\000\002\001\001\000\002\001\001\000"
                + "\002\001\001\000\024\003\033\004\005\005\003\006\017"
                + "\007\004\010\010\011\015\012\011\013\013\001\001\000"
                + "\002\001\001\000\024\003\021\004\005\005\003\006\017"
                + "\007\004\010\010\011\015\012\011\013\013\001\001\000"
                + "\002\001\001\000\024\003\032\004\005\005\003\006\017"
                + "\007\004\010\010\011\015\012\011\013\013\001\001\000"
                + "\024\003\031\004\005\005\003\006\017\007\004\010\010"
                + "\011\015\012\011\013\013\001\001\000\002\001\001\000"
                + "\024\003\030\004\005\005\003\006\017\007\004\010\010"
                + "\011\015\012\011\013\013\001\001\000\024\003\027\004"
                + "\005\005\003\006\017\007\004\010\010\011\015\012\011"
                + "\013\013\001\001\000\002\001\001\000\002\001\001\000"
                + "\002\001\001\000\002\001\001\000\002\001\001\000\002"
                + "\001\001"});

    /**
     * Access to <code>reduce_goto</code> table.
     */
    public short[][] reduce_table() {
        return _reduce_table;
    }

    /**
     * Instance of action encapsulation class.
     */
    protected CUP$parser$actions action_obj;

    /**
     * Action encapsulation object initializer.
     */
    protected void init_actions() {
        action_obj = new CUP$parser$actions(this);
    }

    /**
     * Invoke a user supplied parse action.
     */
    public java_cup.runtime.Symbol do_action(
            int act_num,
            java_cup.runtime.lr_parser parser,
            java.util.Stack stack,
            int top)
            throws java.lang.Exception {
        /* call code in generated class */
        return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
    }

    /**
     * Indicates start state.
     */
    public int start_state() {
        return 0;
    }

    /**
     * Indicates start production.
     */
    public int start_production() {
        return 1;
    }

    /**
     * <code>EOF</code> Symbol index.
     */
    public int EOF_sym() {
        return 0;
    }

    /**
     * <code>error</code> Symbol index.
     */
    public int error_sym() {
        return 1;
    }

    public void report_error(String message, Object info) {

        StringBuilder m = new StringBuilder("Error");

        if (info instanceof java_cup.runtime.Symbol) {

            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);

            if (s.left >= 0) {
                m.append(" in line " + (s.left + 1));
                if (s.right >= 0) {
                    m.append(", column " + (s.right + 1));
                }
            }
        }

        m.append(" : " + message);
        System.err.println(m);
        throw new Error("Syntax error. ");
    }

    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        //System.exit(1);
    }

}

/**
 * Cup generated class to encapsulate user supplied action code.
 */
class CUP$parser$actions {

    private final parser parser;

    /**
     * Constructor
     */
    CUP$parser$actions(parser parser) {
        this.parser = parser;
    }

    /**
     * Method with the actual generated action code.
     */
    public final java_cup.runtime.Symbol CUP$parser$do_action(
            int CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack CUP$parser$stack,
            int CUP$parser$top)
            throws java.lang.Exception {
        /* Symbol object for return from actions */
        java_cup.runtime.Symbol CUP$parser$result;

        /* select the action based on the action number */
        switch (CUP$parser$act_num) {
            /*. . . . . . . . . . . . . . . . . . . .*/
            case 17: // IFFStatements ::= LogicStatements IFF LogicStatements 
            {
                LogicStatement RESULT = null;
                int lleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).left;
                int lright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).right;
                LogicStatement l = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).value;
                int pleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int pright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement p = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = new IFFStatement(l, p);
                CUP$parser$result = new java_cup.runtime.Symbol(9/*IFFStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 16: // ImpliesStatements ::= LogicStatements IMPLIES LogicStatements 
            {
                LogicStatement RESULT = null;
                int lleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).left;
                int lright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).right;
                LogicStatement l = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).value;
                int pleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int pright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement p = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = new ImpliesStatement(l, p);
                CUP$parser$result = new java_cup.runtime.Symbol(8/*ImpliesStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 15: // OrStatements ::= LogicStatements OR LogicStatements 
            {
                LogicStatement RESULT = null;
                int lleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).left;
                int lright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).right;
                LogicStatement l = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).value;
                int pleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int pright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement p = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = new OrStatement(l, p);
                CUP$parser$result = new java_cup.runtime.Symbol(7/*OrStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 14: // AndStatements ::= LogicStatements AND LogicStatements 
            {
                LogicStatement RESULT = null;
                int lleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).left;
                int lright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).right;
                LogicStatement l = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).value;
                int pleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int pright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement p = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = new AndStatement(l, p);
                CUP$parser$result = new java_cup.runtime.Symbol(6/*AndStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 13: // BinaryOpStatements ::= IFFStatements 
            {
                LogicStatement RESULT = null;
                int fleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int fright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement f = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = f;
                CUP$parser$result = new java_cup.runtime.Symbol(3/*BinaryOpStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 12: // BinaryOpStatements ::= ImpliesStatements 
            {
                LogicStatement RESULT = null;
                int ileft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int iright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement i = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = i;
                CUP$parser$result = new java_cup.runtime.Symbol(3/*BinaryOpStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 11: // BinaryOpStatements ::= OrStatements 
            {
                LogicStatement RESULT = null;
                int oleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int oright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement o = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = o;
                CUP$parser$result = new java_cup.runtime.Symbol(3/*BinaryOpStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 10: // BinaryOpStatements ::= AndStatements 
            {
                LogicStatement RESULT = null;
                int aleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int aright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement a = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = a;
                CUP$parser$result = new java_cup.runtime.Symbol(3/*BinaryOpStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 9: // NotStatements ::= NOT LogicStatements 
            {
                LogicStatement RESULT = null;
                int lleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int lright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement l = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = new NotStatement(l);
                CUP$parser$result = new java_cup.runtime.Symbol(4/*NotStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 1)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 8: // UnaryOpStatements ::= NotStatements 
            {
                LogicStatement RESULT = null;
                int nleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int nright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement n = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = n;
                CUP$parser$result = new java_cup.runtime.Symbol(2/*UnaryOpStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 7: // Variables ::= ID 
            {
                LogicStatement RESULT = null;
                int ileft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int iright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                String i = (String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = new Variable(i);
                CUP$parser$result = new java_cup.runtime.Symbol(5/*Variables*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 6: // LogicStatements ::= LBRACKET LogicStatements RBRACKET 
            {
                LogicStatement RESULT = null;
                int lleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 1)).left;
                int lright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 1)).right;
                LogicStatement l = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 1)).value;
                RESULT = l;
                CUP$parser$result = new java_cup.runtime.Symbol(1/*LogicStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 2)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 5: // LogicStatements ::= BinaryOpStatements 
            {
                LogicStatement RESULT = null;
                int bleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int bright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement b = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = b;
                CUP$parser$result = new java_cup.runtime.Symbol(1/*LogicStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 4: // LogicStatements ::= UnaryOpStatements 
            {
                LogicStatement RESULT = null;
                int uleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int uright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement u = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = u;
                CUP$parser$result = new java_cup.runtime.Symbol(1/*LogicStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 3: // LogicStatements ::= FALSITY 
            {
                LogicStatement RESULT = null;
                RESULT = new Falsity();
                CUP$parser$result = new java_cup.runtime.Symbol(1/*LogicStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 2: // LogicStatements ::= TRUTH 
            {
                LogicStatement RESULT = null;
                RESULT = new Truth();
                CUP$parser$result = new java_cup.runtime.Symbol(1/*LogicStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 1: // $START ::= LogicStatements EOF 
            {
                Object RESULT = null;
                int start_valleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 1)).left;
                int start_valright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 1)).right;
                LogicStatement start_val = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 1)).value;
                RESULT = start_val;
                CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 1)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            /* ACCEPT */
            CUP$parser$parser.done_parsing();
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 0: // LogicStatements ::= Variables 
            {
                LogicStatement RESULT = null;
                int vleft = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left;
                int vright = ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right;
                LogicStatement v = (LogicStatement) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).value;
                RESULT = v;
                CUP$parser$result = new java_cup.runtime.Symbol(1/*LogicStatements*/, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).left, ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top - 0)).right, RESULT);
            }
            return CUP$parser$result;

            /* . . . . . .*/
            default:
                throw new Exception(
                        "Invalid action number found in internal parse table");

        }
    }
}
