package lexerAndParser;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 14 14:34:26 GMT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 3;
  public static final int FALSITY = 7;
  public static final int SEMI = 2;
  public static final int FORALL = 11;
  public static final int TRUTH = 6;
  public static final int EOF = 0;
  public static final int IFF = 4;
  public static final int RBRACKET = 14;
  public static final int ID = 16;
  public static final int COMMA = 15;
  public static final int error = 1;
  public static final int IMPLIES = 9;
  public static final int NOT = 10;
  public static final int EQUALS = 8;
  public static final int LBRACKET = 13;
  public static final int THEREEXISTS = 12;
  public static final int OR = 5;
}

